version: 2

sources:

  - name: staging
    database: france-courses-enrollments
    schema: source_tables

    tables:
      - name: courses
      - name: enrollments
      - name: formacode

models:
  - name: stg_courses
    description: "The training courses offered in My Training Account are certified training courses submitted by training organizations via the EDOF portal."
    columns:
      - name: course_month
        data_type: string
        description: "Year and month in which the course was extracted. Example: 2025-03"

      - name: date_extract
        data_type: date
        description: "Date on which the course was extracted. Example: 2025-03-25"

      - name: provider
        data_type: string
        description: "Company providing the course. Example: AFTRAL"

      - name: certification_title
        data_type: string
        description: "Certification Title. Example: Certificate of aptitude for safe driving (CACES) Recommendation 482 category B1: Sequential movement extraction equipment"

      - name: code_certification
        data_type: string
        description: "Certification code corresponding to certification_title. Example: 106655"

      - name: code_rncp
        data_type: string
        description: "National Directory of Professional Certifications Code. Example: -1 (Because it has code_rs)"

      - name: code_rs
        data_type: string
        description: "Certifications listed in the RS inventory. Example: 7041"

      - name: fcod_1
        data_type: string
        description: "It represents the 5 most relevant Formacode codes for each training course. It is like a search word or a classification system to categorise training programs by skills it aims at. Example: 31025 - Data Analytics, 31026 - Data Science"

      - name: fcod_2
        data_type: string
        description: "It represents the 5 most relevant Formacode codes for each training course. It is like a search word or a classification system to categorise training programs by skills it aims at. Example: 31025 - Data Analytics, 31026 - Data Science"

      - name: fcod_3
        data_type: string
        description: "It represents the 5 most relevant Formacode codes for each training course. It is like a search word or a classification system to categorise training programs by skills it aims at. Example: 31025 - Data Analytics, 31026 - Data Science"

      - name: fcod_4
        data_type: string
        description: "It represents the 5 most relevant Formacode codes for each training course. It is like a search word or a classification system to categorise training programs by skills it aims at. Example: 31025 - Data Analytics, 31026 - Data Science"

      - name: fcod_5
        data_type: string
        description: "It represents the 5 most relevant Formacode codes for each training course. It is like a search word or a classification system to categorise training programs by skills it aims at. Example: 31025 - Data Analytics, 31026 - Data Science"

      - name: provider_id
        data_type: string
        description: "Establishment unique ID corresponding to provider. Example: 30540504500603"

      - name: training_id
        data_type: string
        description: "Trianing Id. Example: 30540504500603_ENCH22-14452-RS7041"

  - name: stg_enrollments
    description: ""
    columns:
      - name: year_month
        data_type: date
        description: ""

      - name: code_rncp
        data_type: string
        description: ""

      - name: code_rs
        data_type: string
        description: ""

      - name: certification_title
        data_type: string
        description: ""

      - name: code_certification
        data_type: string
        description: ""

      - name: provider_id
        data_type: string
        description: ""

      - name: provider
        data_type: string
        description: ""

      - name: training_entries
        data_type: int64
        description: ""

      - name: fcod_1
        data_type: string
        description: ""

      - name: fcod_2
        data_type: string
        description: ""

      - name: fcod_3
        data_type: string
        description: ""

      - name: fcod_4
        data_type: string
        description: ""

      - name: fcod_5
        data_type: string
        description: ""

      - name: rn
        data_type: int64
        description: ""

  - name: dim_courses
    description: ""
    columns:
      - name: course_month
        data_type: string
        description: ""

      - name: formacode
        data_type: string
        description: ""

      - name: total_nb_trianings
        data_type: int64
        description: ""

      - name: total_nb_providers
        data_type: int64
        description: ""

      - name: total_nb_certifications
        data_type: int64
        description: ""

      - name: training_provider_ratio
        data_type: float64
        description: ""

      - name: formacode_description
        data_type: string
        description: ""

      - name: formacode_field
        data_type: string
        description: ""

  - name: dim_formacode
    description: ""
    columns:
      - name: formacode
        data_type: string
        description: ""

      - name: description_en
        data_type: string
        description: ""

      - name: field_en
        data_type: string
        description: ""

  - name: fact_enrollments
    description: ""
    columns:
      - name: year_month
        data_type: date
        description: ""

      - name: formacode
        data_type: string
        description: ""

      - name: total_enrollments
        data_type: int64
        description: ""

      - name: total_nb_providers
        data_type: int64
        description: ""

      - name: total_nb_certifications
        data_type: int64
        description: ""

      - name: enrollments_provider_ratio
        data_type: float64
        description: ""

      - name: formacode_description
        data_type: string
        description: ""

      - name: formacode_field
        data_type: string
        description: ""
