version: 2

sources:

  - name: staging
    database: france-courses-enrollments
    schema: source_tables

    tables:
      - name: courses
      - name: enrollments
      - name: formacode

  - name: staging_tmp
    database: france-courses-enrollments
    schema: staging

    tables:
      - name: formacode